# Introduction

This book provides a visual story of efforts to quantify the influence of habitat quality on rates of superimposition and strength of density-dependence (Ricker *b*) for Yellowstone cutthroat trout (YCT). All redd count data was collected by the Wyoming Game and Fish Department. This project builds off of previous efforts to quantify the effects of [changing climate and water management on population productivity of YCT](https://j-baldock.github.io/YCT-ReddCounts-Ricker/).

Access the GitHub repo here: <https://github.com/j-baldock/Super-Ricker>

*This information is preliminary or provisional and is subject to revision. It is being provided to meet the need for timely best science. The information has not received final approval by the U.S. Geological Survey (USGS) and is provided on the condition that neither the USGS nor the U.S. Government shall be held liable for any damages resulting from the authorized or unauthorized use of the information.*

Project team: Jeff Baldock (ORISE; USGS, NOROCK) & Tim Cline (MSU)

------------------------------------------------------------------------

<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne">

Session Information

</button>

:::: {#collapseOne .accordion-collapse .collapse}
<div>

```{r}
sessionInfo()
```

</div>
::::
